### ISSUE TITLE
ENH: cloud function to go autonomous

### ISSUE THREAD

**Issue by jschrempp** [BobGlicksman/Robotics#16]
I don't always have my Android device with me. A cloud exposed function to go into Autonomous mode would make it easier for me to experiment with the robot.

**Comment by BobGlicksman** [comment]
sure - add it in. It won't be trivial, however, because of the semiautomatic mode. Perhaps you should add a compile switch to enable automatic mode and also enable Particle.function().


-----Original Message-----
